name: init-node
description: Initialise Node & NPM for the repository

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        cache: pnpm
        node-version-file: .nvmrc
    - run: pnpm install --frozen-lockfile
      shell: bash
